////
This is the base template for Hazelcast integration module guides.

You can clone this repository, work on it and create your guide, and then push to a new repository.
////

:github-address: [github-repo-address-of-your-guide]

:templates-url: https://raw.githubusercontent.com/hazelcast-guides/adoc-templates/master

// Use this relative url if you are going to publish the guide on the guides site.
// Note that this url will not work locally and raise asciidoctor errors.
// So, complete the guide with the above url and set the below one just before 
// publishing on the guides site.
//
// :templates-url: templates:ROOT:page$/

= Deploying Hazelcast Cluster on Cloud using Terraform

// Content entered directly below the header but before the first section heading is called the preamble.

include::{templates-url}/link-to-repo.adoc[]

== What You’ll Learn

You will learn how to deploy a Hazelcast cluster and Hazelcast Management Center on AWS, Azure and GCP using Terraform. The Terraform files will have the necessary resources defined, you will use your credentials to give Terraform permissions to create resources on your behalf. After you run the Terraform and create a cluster on Cloud, you will be able to monitor the cluster using Hazelcast Management Center. You can modify the Terraform files to create new resources or destroy whole cluster.

== Prerequisites

- https://www.terraform.io/downloads.html#undefined[Terraform v0.13+]

- Access to one of the following AWS, Azure or GCP. The account must have permissions to create resources.

== Giving Access to Terraform

Cloud providers offer different ways of authenticating Terraform to create resources. Below some of them are presented.

=== Configuring AWS

For AWS you can set environment variables `AWS_ACCESS_KEY_ID` and  `AWS_SECRET_ACCESS_KEY. Terraform will use these environment variables to create resources. Run the following commands to authenticate.

[source, shell]
----
$ export AWS_ACCESS_KEY_ID="XXXXXXXXXXXX"
$ export AWS_SECRET_ACCESS_KEY="XXXXXXXXXXXXXXXX"
----

You can find other ways to authenticate at https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication[Terraform AWS authentication]

=== Configuring Azure

If you are using a user account, you can login by https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest#install[Azure CLI]. Run the following commands to authenticate.
[source, shell]
----
$ az login
----

If you have multiple subscriptions and multiple tenants you can choose one by adding following lines to `main.tf`.
[source, shell]
----
provider "azurerm" {
  version = "=2.23.0"
  features {}

  subscription_id = "00000000-0000-0000-0000-000000000000"
  tenant_id       = "11111111-1111-1111-1111-111111111111"

}

----

If you want to authenticate through managed identities and service principals, please refer to https://www.terraform.io/docs/providers/azurerm/index.html#authenticating-to-azure[Authenticating to Azure]

=== Configuring GCP

You can use a service accounts authenticate Terraform. Get a service account key file, if you don't know how refer to https://cloud.google.com/iam/docs/creating-managing-service-account-keys#creating_service_account_keys[GCP Creating Service Account Keys]. After you have created a key file, in `gcp/main.tf` put your key file as follows.

[source,terraform]
----
provider "google" {
  version = "3.5.0"

  credentials = file("YOUR-KEY-FILE.json")
  batching {
    enable_batching = "false"
  }
  project = var.project-id
  region  = var.region
  zone    = var.zone
}
----

=== Deploying the Cluster with Terraform

After you have authenticated your preferred cloud provider, `cd` into the directory of that provider.

[NOTE]
====
If you are using a paid subscription, you may be charged for the resources that will be created in this tutorial. However this guide can be completed using free tier subscriptions provided by https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc[AWS], https://azure.microsoft.com/en-us/free/[Azure] and https://cloud.google.com/free[GCP].
====

Run the following to initialize Terraform.
[source, shell]
----
$ terraform init
----

Run the following to create an execution plan. This command will not create any resources, it only shows what actions Terraform will perform if `terraform apply` is run.
[source, shell]
----
$ terraform plan
----

Apply your Terraform configuration.
[source, shell]
----
$ terraform apply
----
The outputs should be similar to the following:

[source, shell]
----
----
After this step if no errors occured, you will have deployed 2 Hazelcast cluster members and a Hazelcast Management Center. You can view the state of your cluster by opening a browser and typing:
[source]
----
http://PUBLIC-IP-OF-MANAGEMENT-CENTER:8080
----

You can change the input variables in `variables.tf` file by updating `example.tfvars`. After the changes the new desired state will be applied by `terraform apply`. You can use ssh to examine VM's by using the IP's provided in the output of `terraform apply`. If you cannot find the outputs you can run 'terraform show' to see current state of you configuration.

When you are done with the guide run the following to delete all the resources created.
[source, shell]
----
$ terraform destroy
----

== Summary

// Provide a quick summary

== See Also

// Add some links to resources, such as other related guides.
// Use relative links used on the home page (see https://raw.githubusercontent.com/hazelcast-guides/guides-site/master/home/modules/ROOT/pages/index.adoc)

- xref:hazelcast-embedded-springboot:ROOT:index.adoc[Hazelcast in SpringBoot]
- xref:hazelcast-quarkus:ROOT:index.adoc[Hazelcast Client for Quarkus] 
