name: tf-guide-aws
on:
  workflow_dispatch:
  push:
    paths:
      - 'aws/**'
  pull_request:
    paths:
      - 'aws/**'

jobs:
  build:
    defaults:
      run:
        shell: bash
    env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout to repo 
        uses: actions/checkout@v2

      - name : Set-up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0

      - name: Configure terraform.tfvars
        run: |
          sed -i -e "s~#\"id_rsa\"~\"id_rsa\"~g" aws/terraform.tfvars
          sed -i -e "s~#\"\~/\.ssh\"~\"\~/\.ssh\"~g" aws/terraform.tfvars

      - name: Use unique prefix for resources
        run: |
          sed -i -e "s~\"hazelcast\"~\"${GITHUB_WORKFLOW}-${GITHUB_RUN_ID}\"~g" aws/terraform.tfvars

      - name: Terraform Init
        run: cd aws && terraform init

      - name: Terraform Format
        run: cd aws  && terraform fmt

      - name: Install private key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa 
          known_hosts: " "

      - name: Install public key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          name: id_rsa.pub 
          known_hosts: " "

      - name: Terraform Apply
        run: |
          cd aws  && terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ always() }}
        run: |
          cd aws && terraform destroy -auto-approve
